dependencies {
    implementation project(':model')
    implementation 'org.springframework:spring-context'
    implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
    implementation 'jakarta.persistence:jakarta.persistence-api'
    implementation 'org.postgresql:r2dbc-postgresql' // Deactivated PostgreSQL
    implementation 'io.r2dbc:r2dbc-h2' // Added H2 R2DBC driver
    implementation 'org.reactivecommons.utils:object-mapper-api:0.1.0'

    testImplementation 'org.reactivecommons.utils:object-mapper:0.1.0'
}

